swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /api/v1

paths:

  '/':
    get:
      operationId: app.get
      summary: Root path.
      responses:
        '200':
          description: Returns an empty object.

  '/users/{username}':
    get:
      tags:
        - users
      operationId: app.get_user
      summary: Get a specific user information.
      parameters:
        - name: username
          in: path
          description: The username.
          required: true
          type: string
      responses:
        '200':
          description: Returns a user.
          # schema:
          #   type: object
          #   items:
          #     $ref: '#/definitions/User'

  '/users':
    get:
      tags:
        - users
      operationId: app.get_users
      summary: Get users information.
      responses:
        '200':
          description: Returns a list of users.
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      tags:
        - users
      operationId: app.post_users
      summary: Post user information.
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Returns a status object.


definitions:

  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      email:
        type: string
      dob:
        type: string
      address:
        type: string

  Status:
    type: object
    properties:
        code:
          type: integer
          format: int64
        message:
          type: string
